#include QMK_KEYBOARD_H
#include "quantum.h"


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// Tap Dance declarations

void space(qk_tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        SEND_STRING(" ");
        reset_tap_dance(state);
    }

    if (state->count == 2) {
    	SEND_STRING(". ");
    	reset_tap_dance(state);
    }
}

enum {
    TD_ESC_CAPS,
    TD_C_COPY,
    TD_V_PASTE,
    TD_KCMINS_LOCK,
    TD_I_QU,
    CT_SPACE,
};

// Tap Dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Escape, twice for Caps Lock
    [TD_ESC_CAPS] = ACTION_TAP_DANCE_DOUBLE(KC_ESC, KC_CAPS),
    [TD_C_COPY] = ACTION_TAP_DANCE_DOUBLE(KC_C, LCTL(KC_C)),
    [TD_V_PASTE] = ACTION_TAP_DANCE_DOUBLE(KC_V, LCTL(KC_V)),
    [TD_KCMINS_LOCK] = ACTION_TAP_DANCE_DOUBLE(KC_MINS, LGUI(KC_L)),
    [TD_I_QU] = ACTION_TAP_DANCE_DOUBLE(KC_I, LSFT(KC_MINS)),
    [CT_SPACE] = ACTION_TAP_DANCE_FN(space),
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(TD(TD_ESC_CAPS), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, TD(TD_KCMINS_LOCK), KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, TD(TD_I_QU), KC_O, KC_P, KC_LBRC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LGUI, KC_Z, KC_X, TD(TD_C_COPY), TD(TD_V_PASTE), KC_B, KC_MUTE, RCS(KC_M), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_DEL, KC_LALT, KC_LCTL, TT(1), TD(CT_SPACE), KC_ENT, TT(2), KC_BSPC, KC_RALT),
	[1] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_RCTL, KC_NO, KC_NO, LCTL(LGUI(KC_LEFT)), LCTL(LGUI(KC_RGHT)), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD, KC_NUBS, LSFT(KC_NUBS), RALT(KC_7), RALT(KC_0), RALT(KC_8), RALT(KC_9), KC_TRNS, KC_TRNS, KC_NUHS, KC_UNDS, KC_PLUS, KC_TRNS, KC_RCBR, KC_PIPE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_TRNS, KC_TRNS),
	[2] = LAYOUT(PB_1, PB_2, PB_3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, PB_4, PB_5, PB_6, KC_NO, KC_NO, KC_PMNS, KC_NO, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, PB_7, PB_8, PB_9, KC_NO, KC_PSLS, KC_PPLS, KC_NO, KC_NO, KC_UP, KC_P1, KC_P2, KC_P3, PB_10, PB_11, PB_12, KC_NO, KC_PAST, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_P0, KC_PDOT, KC_TRNS, KC_TRNS, MO(3), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};